app <- ShinyDriver$new("../", seed = 123456)
app$snapshotInit("mytest")

app$snapshot()
app$setInputs(username = "guest")
app$setInputs(password = "guest")
app$setInputs(btn_login = "click")
app$snapshot()
app$setInputs(`applogic-num` = 10)
app$setInputs(`applogic-btn_sim` = "click")
app$snapshot()
app$setInputs(lnk_pwd = "click")
app$snapshot()
app$setInputs(`chgpassword-oldpwd` = "guest")
app$setInputs(`chgpassword-newpwd1` = "holahola")
app$setInputs(`chgpassword-newpwd2` = "holahola")
app$setInputs(`chgpassword-btn_pwd` = "click")
app$snapshot()
app$setInputs(lnk_backapp = "click")
app$snapshot()
app$setInputs(lnk_exit = "click")
app$snapshot()
app$setInputs(username = "nouser")
app$setInputs(password = "holahola")
app$setInputs(btn_login = "click")
app$setInputs(btn_login = "click")
app$setInputs(btn_login = "click")
app$setInputs(btn_login = "click")
app$snapshot()
